name: Web-to-API Tests
on: [push]

jobs:
  test:
    name: Run TestCafe Tests
    runs-on: windows-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v1
      - name: Run tests
        uses: DevExpress/testcafe-action@latest
        with:
            args: "chrome tests"
      - uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome fixture.js -s takeOnFails=true -q -c 3"
      - uses: DevExpress/testcafe-action@latest
        with:
          version: "1.6.0"
          args: "chrome tests"
